### ISSUE TITLE
Package import fails without MPP installed

### ISSUE THREAD

**Issue by EliJDonahue** [AngelaIp/aras-image-uploader-for-tech-docs#4]
### Expected Behavior
Package import should succeed without error when the target Aras install meets the documented prerequisites:

1. Aras Innovator installed (version 11.0 SPx preferred)
2. Aras Package Import tool
3. Import package of this project

### Actual Behavior
The following import error occurs if MPP is not installed in the target Aras database:

![Import Error](http://community.aras.com/wp-content/uploads/2017/12/import-error.png)

This is because the ItemType references the Manufacturing Engineering identity for TOC access and Can Add permission. The Manufacturing Engineering identity only exists in systems where MPP is installed.

### Steps to Reproduce 

1. Import the project package into a database that does not have MPP installed.

### Proposed Solution
Since this project can be used with the MPP or Technical Documentation applications, the default TOC access and permissions should reference a common identity or add a custom identity. That way the project can be used in a database that has only Technical Documentation installed and not MPP.

The readme documentation should also be updated to reflect that MPP and/or Technical Documentation must be installed as a prerequisite.

I'm working on a fix for this issue and will submit a pull request with my proposed fix.

**Comment by AngelaIp** [comment]
Closing the issue, as it was resolved by pull request [#5](https://github.com/AngelaIp/aras-image-uploader-for-tech-docs/pull/5).
